### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by wsman217** [XSpigot/XPlay#2]
Ok so I have multiple issues. First off being the fact that I submitted a pull request and instead of merging it you not only deleted it you also blatantly pasted the code directly the same way into your files without giving any credit. I took well over an hour and a half to sit down and rewrite that code to give you some pointers. 
Second off this bit of code here, 
`private void setUpDependencies() {
        //Check If Vault Is Installed
        if (Bukkit.getPluginManager().getPlugin("Vault") != null) {
            getLogger().log(Level.INFO, "Connected Into Vault");
        } else {
            getLogger().log(Level.SEVERE, "Vault Is Not Installed! Disabling Plugin");
            Bukkit.getPluginManager().disablePlugin(this);
        }
        //Check If Placeholder API Is Installed
        if (Bukkit.getPluginManager().getPlugin("PlaceholderAPI") != null) {
            getLogger().log(Level.INFO, "Connected Into Placeholder API");
            Bukkit.getPluginManager().registerEvents(this, this);
        }
        //Check If World Edit Is Installed
        if (Bukkit.getPluginManager().getPlugin("WorldEdit") != null) {
            getLogger().log(Level.INFO, "Connected Into World Edit");
            Bukkit.getPluginManager().registerEvents(this, this);
        }
        //Check If Protocol Lib Is Installed
        if (Bukkit.getPluginManager().getPlugin("ProtocolLib") != null) {
            getLogger().log(Level.INFO, "Connected Into Protocol Lib");
            Bukkit.getPluginManager().registerEvents(this, this);
        }
        //Check If Via Version Is Installed
        if (Bukkit.getPluginManager().getPlugin("ViaVersion") != null) {
            getLogger().log(Level.INFO, "Connected Into Via Version");
            Bukkit.getPluginManager().registerEvents(this, this);
        }
        //Check If Plot Squared Is Installed
        if (Bukkit.getPluginManager().getPlugin("PlotSquared") != null) {
            getLogger().log(Level.INFO, "Connected Into Plot Squared");
            Bukkit.getPluginManager().registerEvents(this, this);
        }
    }`
    You are registering your main class as a listener multiple times, so when you actually put an event handler in there it will get called multiple times. Along with this, this is not a good way to form your code. Instead of putting listeners in the main class put them in another class. Try and make each class have its own single purpose. So 1 class handles 1 command another handles another command and another handles listening to events that are doing similar things.

**Comment by XSpigot** [comment]
So sorry about that, I was having a problem with Github where it wanted me to manually delete some files, and better yet (sarcasm), it decided to not allow me to delete anything! So, I decided to TRY Github Desktop, which has never worked for me, so obviously, why would it work now. So, I decided to download your entire fork, and rewrite it from there. In all the mess, I must have forgotten to credit you! So sorry about that, I will make sure to fix that first thing (Spigot, Github, Wiki, Source)! Also, I will make sure to change my code to include separate classes! Again, I cannot state how much you have helped me with this project! Thank you!

**Comment by wsman217** [comment]
It's all good was just a little annoying to see also do you use IntelliJ? If so it has a built in Git client.

**Comment by XSpigot** [comment]
Yes, but that's the problem, it won't load. It gives me an error (Invalid Authentication Data 404 Not Found - Not Found). Do you know a fix for this? It happens on both token access and login information.

**Comment by XSpigot** [comment]
Never Mind! I Finally Figured Out The Problem!
